# Generated by Django 3.0.8 on 2020-09-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KirktonApp', '0002_userprofile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
